import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS } from '../theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.white,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderBottomWidth: 1,
        borderBottomColor: COLORS.slate100,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    headerTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: COLORS.slate900,
    },
    content: {
        padding: 20,
    },
    imageSection: {
        gap: 16,
        marginBottom: 24,
    },
    imageContainer: {
        width: '100%',
        aspectRatio: 4 / 3,
        backgroundColor: COLORS.slate900,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.slate100, // clinical-border
        overflow: 'hidden',
        position: 'relative',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    mainImage: {
        width: '100%',
        height: '100%',
    },
    boundingBox: {
        position: 'absolute',
        borderRadius: 2,
    },
    boxLabel: {
        position: 'absolute',
        top: -30, // move it higher
        left: '50%',
        minWidth: 80, // Ensure minimum width
        transform: [{ translateX: -40 }], // Center based on minWidth
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        elevation: 1,
        alignItems: 'center',
    },
    boxLabelText: {
        color: 'white',
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    zoomHint: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        padding: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.slate100,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: COLORS.slate100,
        padding: 4,
        borderRadius: 12,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 8,
    },
    toggleButtonActive: {
        backgroundColor: COLORS.white,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        elevation: 1,
    },
    toggleText: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.slate500,
    },
    toggleTextActive: {
        color: COLORS.medicalBlue,
    },
    statsGrid: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 32,
    },
    statCard: {
        flex: 1,
        backgroundColor: COLORS.clinicalGrey,
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.clinicalBorder,
        gap: 4,
    },
    statLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: COLORS.slate500,
        letterSpacing: 0.5,
        textTransform: 'uppercase',
    },
    statRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    statLarge: {
        fontSize: 28,
        fontWeight: '800', // extrabold
        color: COLORS.slate900,
    },
    statIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 16,
        paddingHorizontal: 4,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: COLORS.slate900,
    },
    sectionSubtitle: {
        fontSize: 12,
        fontWeight: '500',
        color: COLORS.slate500,
    },
    dateText: {
        fontSize: 12,
        fontWeight: '600',
        color: COLORS.slate400,
    },
    findingsList: {
        gap: 12,
    },
    findingCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: COLORS.clinicalGrey,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.clinicalBorder,
    },
    healthyCard: {
        opacity: 0.75,
        // grayscale logic can't be easily done on style, opacity works best
    },
    findingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    findingIconBox: {
        width: 48,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    findingTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: COLORS.slate900,
    },
    findingDesc: {
        fontSize: 12,
        color: COLORS.slate500,
    },
    findingRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    percentText: {
        fontSize: 14,
        fontWeight: '800',
    },
    probLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: COLORS.slate400,
        textTransform: 'uppercase',
    },
    emptyBox: {
        padding: 20,
        alignItems: 'center',
    },
    emptyText: {
        color: COLORS.slate500,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: COLORS.slate100,
        paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    },
    downloadButton: {
        backgroundColor: COLORS.medicalBlue,
        height: 56,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        shadowColor: COLORS.medicalBlue,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
        marginBottom: 16,
    },
    downloadButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '700',
    },
    versionText: {
        textAlign: 'center',
        fontSize: 10,
        fontWeight: '700',
        color: COLORS.slate400,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    fullScreenModal: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'black',
        zIndex: 100,
    },
    fsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        zIndex: 10,
    },
    fsCloseBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fsTitle: {
        color: 'white',
        fontSize: 18,
        fontWeight: '700',
    },
    fsImageContainer: {
        flex: 1,
        justifyContent: 'center',
        position: 'relative',
        width: '100%',
        height: '100%',
    },
    fsImage: {
        width: '100%',
        height: '100%',
    },
    fsFooter: {
        padding: 24,
        alignItems: 'center',
    },
});
